name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs daily at midnight UTC
  workflow_dispatch:                # Also allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          base: activity, repositories
          plugin_lines: yes
