name: GitHub Metrics
on:
  schedule: [{ cron: "0 0 * * *" }] # daily at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, repositories
          plugin_lines: yes
